"""
Django MVT (Model-View-Template) Pattern
Explanation: Django, a high-level Python web framework, follows a slightly modified version of the MVC pattern called MVT:

Model: Just like in MVC, it represents the data structure and business logic. In Django, it's typically defined in models.py and interacts with the database using Django's ORM (Object-Relational Mapping).
View: In Django, the View is more focused on processing the data and business logic. It's defined in views.py and handles HTTP requests, interacts with the Model, and returns a response.
Template: This corresponds to the View in MVC but is specifically concerned with rendering HTML. Django's templates are defined in .html files and use Django's template language to display data dynamically.
Example:

When a user accesses a URL, Django’s View processes the request, interacts with the Model if necessary, and returns an HTML response generated by a Template.
"""